### ISSUE TITLE
KDE inline reply

### ISSUE THREAD

**Issue by daffamumtaz2361** [Hill-98/node-dbus-notifier#2]
I know it is non standard, but it would be cool to have this feature. All you need to do is add an action with `inline-reply` as the identifier, then listen to `NotificationReplied` signal. You can check if it's supported by calling `GetCapabilities` method and checking if `inline-reply` is on the array.

**Comment by Hill-98** [comment]
That's great, I use KDE myself so I've been wanting to add features to it that are specific to a particular desktop environment, but I haven't found the documentation for KDE notifications (if you have them).

I'll try adding this feature when I have some free time.

**Comment by daffamumtaz2361** [comment]
That's great! I've actually modified your code and got it working. I'll open a PR
