### ISSUE TITLE
Callback are called multiple times when using replacesId

### ISSUE THREAD

**Issue by daffamumtaz2361** [Hill-98/node-dbus-notifier#8]
When grouping multiple notification using `replacesId`, the action callback are triggered multiple as many as the grouped notification.

I assume this is because the callbacks are defined multiple times as well, but there should be a way to prevent calling all the redundant callback if they have the same `replacesId`.

My expected outcome is only the last callback getting called

**Comment by Hill-98** [comment]
I don't quite understand your use case, can you give me an example?

**Comment by daffamumtaz2361** [comment]
Sorry if I'm not clear enough, here's a simple reproduction snippet

```js
const { Notify } = require('node-dbus-notifier');

async function sendNotif(body) {
  const notif = new Notify({
    summary: 'title',
    replacesId: 54327,
    body,
    timeout: 5000,
  });

  notif.setDefaultAction(() => {
    console.log('clicked', body);
  });

  return notif.show();
}

setTimeout(() => sendNotif('first this'), 0);
setTimeout(() => sendNotif('then this'), 1000);
setTimeout(() => sendNotif('try clicking this'), 2000);
```

The notification will be shown and change twice, then if it's clicked, it will output this

```
clicked first this
clicked then this
clicked try clicking this
```

All 3 callbacks are called, where I expected only the last callback to be called

```
clicked try clicking this
```

**Comment by Hill-98** [comment]
This is expected behavior, rather than letting the library fix it, because the library just accepts the event, calls the callback.

You should consider maintaining notification state inside your application.

**Comment by daffamumtaz2361** [comment]
Yeah I thought that's what expected, but consider this as a feature request to add callback deduplication

**Comment by daffamumtaz2361** [comment]
I could open a PR to add it, but if you feel it's out of scope, you could close this issue

**Comment by Hill-98** [comment]
I tried to solve it in a less intrusive way, you can test it with the latest git version.

Edit: set `closeReplacedNotify` to `true`

**Comment by daffamumtaz2361** [comment]
It works great, thank you
